# Generated by Django 3.1.5 on 2021-05-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mailbox', models.CharField(max_length=200)),
                ('birth', models.DateField()),
                ('balance', models.FloatField()),
                ('mgr', models.IntegerField()),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('articleTitle', models.CharField(max_length=200)),
                ('articleContent', models.TextField()),
                ('pubDate', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.userinfo')),
            ],
        ),
    ]
