# Generated by Django 3.1.5 on 2021-05-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210502_2146'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
    ]
